  name: publish-to-npm
  on:
    push:
      branches:
        - 'main'

  jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: yarn install
        - run: yarn test
        - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}
        - name: Conventional Changelog Action
          id: changelog
          uses: TriPSs/conventional-changelog-action@v3
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            release-count: 1
            output-file: "false"
        - name: Create Github Release
          if: steps.publish.outputs.version != steps.publish.outputs['old-version']
          uses: ncipollo/release-action@v1
          with:
            body: ${{ steps.changelog.outputs.clean_changelog }}
            tag: v${{ steps.publish.outputs.version }}
            commit: master
            token: ${{ secrets.GITHUB_TOKEN }}
